/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125WorkspaceRouteImport } from './routes/{-$locale}/workspace'
import { Route as Char123LocaleChar125ProjectsRouteImport } from './routes/{-$locale}/projects'
import { Route as Char123LocaleChar125ImpressumRouteImport } from './routes/{-$locale}/impressum'
import { Route as Char123LocaleChar125DatenschutzRouteImport } from './routes/{-$locale}/datenschutz'
import { Route as Char123LocaleChar125CvRouteImport } from './routes/{-$locale}/cv'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGraphqlRouteImport } from './routes/api/graphql'
import { Route as ApiFileUploadsRouteImport } from './routes/api/file-uploads'
import { Route as Char123LocaleChar125WorkspaceIndexRouteImport } from './routes/{-$locale}/workspace/index'
import { Route as Char123LocaleChar125WorkspaceVisitorChatsRouteImport } from './routes/{-$locale}/workspace/visitor-chats'
import { Route as Char123LocaleChar125WorkspaceTravelRouteImport } from './routes/{-$locale}/workspace/travel'
import { Route as Char123LocaleChar125WorkspaceTodosRouteImport } from './routes/{-$locale}/workspace/todos'
import { Route as Char123LocaleChar125WorkspaceTaxRouteImport } from './routes/{-$locale}/workspace/tax'
import { Route as Char123LocaleChar125WorkspaceSoftwareRouteImport } from './routes/{-$locale}/workspace/software'
import { Route as Char123LocaleChar125WorkspaceProjectsRouteImport } from './routes/{-$locale}/workspace/projects'
import { Route as Char123LocaleChar125WorkspaceMedicalRouteImport } from './routes/{-$locale}/workspace/medical'
import { Route as Char123LocaleChar125WorkspaceMediaRouteImport } from './routes/{-$locale}/workspace/media'
import { Route as Char123LocaleChar125WorkspaceLogsRouteImport } from './routes/{-$locale}/workspace/logs'
import { Route as Char123LocaleChar125WorkspaceInventoryRouteImport } from './routes/{-$locale}/workspace/inventory'
import { Route as Char123LocaleChar125WorkspaceFitnessRouteImport } from './routes/{-$locale}/workspace/fitness'
import { Route as Char123LocaleChar125WorkspaceFinancesRouteImport } from './routes/{-$locale}/workspace/finances'
import { Route as Char123LocaleChar125WorkspaceCvRouteImport } from './routes/{-$locale}/workspace/cv'
import { Route as Char123LocaleChar125WorkspaceCompassRouteImport } from './routes/{-$locale}/workspace/compass'
import { Route as ApiFileUploadsFileUploadIdRouteImport } from './routes/api/file-uploads_.$fileUploadId'
import { Route as Char123LocaleChar125WorkspaceProjectsProjectIdRouteImport } from './routes/{-$locale}/workspace/projects_.$projectId'
import { Route as Char123LocaleChar125WorkspaceInventoryItemIdRouteImport } from './routes/{-$locale}/workspace/inventory_.$itemId'
import { Route as Char123LocaleChar125WorkspaceAssistantChatIdRouteImport } from './routes/{-$locale}/workspace/assistant.$chatId'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125WorkspaceRoute =
  Char123LocaleChar125WorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ProjectsRoute =
  Char123LocaleChar125ProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ImpressumRoute =
  Char123LocaleChar125ImpressumRouteImport.update({
    id: '/impressum',
    path: '/impressum',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125DatenschutzRoute =
  Char123LocaleChar125DatenschutzRouteImport.update({
    id: '/datenschutz',
    path: '/datenschutz',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125CvRoute = Char123LocaleChar125CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => Char123LocaleChar125Route,
} as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphqlRoute = ApiGraphqlRouteImport.update({
  id: '/api/graphql',
  path: '/api/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileUploadsRoute = ApiFileUploadsRouteImport.update({
  id: '/api/file-uploads',
  path: '/api/file-uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125WorkspaceIndexRoute =
  Char123LocaleChar125WorkspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125WorkspaceRoute,
  } as any)
const Char123LocaleChar125WorkspaceVisitorChatsRoute =
  Char123LocaleChar125WorkspaceVisitorChatsRouteImport.update({
    id: '/visitor-chats',
    path: '/visitor-chats',
    getParentRoute: () => Char123LocaleChar125WorkspaceRoute,
  } as any)
const Char123LocaleChar125WorkspaceTravelRoute =
  Char123LocaleChar125WorkspaceTravelRouteImport.update({
    id: '/travel',
    path: '/travel',
    getParentRoute: () => Char123LocaleChar125WorkspaceRoute,
  } as any)
const Char123LocaleChar125WorkspaceTodosRoute =
  Char123LocaleChar125WorkspaceTodosRouteImport.update({
    id: '/todos',
    path: '/todos',
    getParentRoute: () => Char123LocaleChar125WorkspaceRoute,
  } as any)
const Char123LocaleChar125WorkspaceTaxRoute =
  Char123LocaleChar125WorkspaceTaxRouteImport.update({
    id: '/tax',
    path: '/tax',
    getParentRoute: () => Char123LocaleChar125WorkspaceRoute,
  } as any)
const Char123LocaleChar125WorkspaceSoftwareRoute =
  Char123LocaleChar125WorkspaceSoftwareRouteImport.update({
    id: '/software',
    path: '/software',
    getParentRoute: () => Char123LocaleChar125WorkspaceRoute,
  } as any)
const Char123LocaleChar125WorkspaceProjectsRoute =
  Char123LocaleChar125WorkspaceProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => Char123LocaleChar125WorkspaceRoute,
  } as any)
const Char123LocaleChar125WorkspaceMedicalRoute =
  Char123LocaleChar125WorkspaceMedicalRouteImport.update({
    id: '/medical',
    path: '/medical',
    getParentRoute: () => Char123LocaleChar125WorkspaceRoute,
  } as any)
const Char123LocaleChar125WorkspaceMediaRoute =
  Char123LocaleChar125WorkspaceMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => Char123LocaleChar125WorkspaceRoute,
  } as any)
const Char123LocaleChar125WorkspaceLogsRoute =
  Char123LocaleChar125WorkspaceLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => Char123LocaleChar125WorkspaceRoute,
  } as any)
const Char123LocaleChar125WorkspaceInventoryRoute =
  Char123LocaleChar125WorkspaceInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => Char123LocaleChar125WorkspaceRoute,
  } as any)
const Char123LocaleChar125WorkspaceFitnessRoute =
  Char123LocaleChar125WorkspaceFitnessRouteImport.update({
    id: '/fitness',
    path: '/fitness',
    getParentRoute: () => Char123LocaleChar125WorkspaceRoute,
  } as any)
const Char123LocaleChar125WorkspaceFinancesRoute =
  Char123LocaleChar125WorkspaceFinancesRouteImport.update({
    id: '/finances',
    path: '/finances',
    getParentRoute: () => Char123LocaleChar125WorkspaceRoute,
  } as any)
const Char123LocaleChar125WorkspaceCvRoute =
  Char123LocaleChar125WorkspaceCvRouteImport.update({
    id: '/cv',
    path: '/cv',
    getParentRoute: () => Char123LocaleChar125WorkspaceRoute,
  } as any)
const Char123LocaleChar125WorkspaceCompassRoute =
  Char123LocaleChar125WorkspaceCompassRouteImport.update({
    id: '/compass',
    path: '/compass',
    getParentRoute: () => Char123LocaleChar125WorkspaceRoute,
  } as any)
const ApiFileUploadsFileUploadIdRoute =
  ApiFileUploadsFileUploadIdRouteImport.update({
    id: '/api/file-uploads_/$fileUploadId',
    path: '/api/file-uploads/$fileUploadId',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125WorkspaceProjectsProjectIdRoute =
  Char123LocaleChar125WorkspaceProjectsProjectIdRouteImport.update({
    id: '/projects_/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => Char123LocaleChar125WorkspaceRoute,
  } as any)
const Char123LocaleChar125WorkspaceInventoryItemIdRoute =
  Char123LocaleChar125WorkspaceInventoryItemIdRouteImport.update({
    id: '/inventory_/$itemId',
    path: '/inventory/$itemId',
    getParentRoute: () => Char123LocaleChar125WorkspaceRoute,
  } as any)
const Char123LocaleChar125WorkspaceAssistantChatIdRoute =
  Char123LocaleChar125WorkspaceAssistantChatIdRouteImport.update({
    id: '/assistant/$chatId',
    path: '/assistant/$chatId',
    getParentRoute: () => Char123LocaleChar125WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/api/file-uploads': typeof ApiFileUploadsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/tts': typeof ApiTtsRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/cv': typeof Char123LocaleChar125CvRoute
  '/{-$locale}/datenschutz': typeof Char123LocaleChar125DatenschutzRoute
  '/{-$locale}/impressum': typeof Char123LocaleChar125ImpressumRoute
  '/{-$locale}/projects': typeof Char123LocaleChar125ProjectsRoute
  '/{-$locale}/workspace': typeof Char123LocaleChar125WorkspaceRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/file-uploads/$fileUploadId': typeof ApiFileUploadsFileUploadIdRoute
  '/{-$locale}/workspace/compass': typeof Char123LocaleChar125WorkspaceCompassRoute
  '/{-$locale}/workspace/cv': typeof Char123LocaleChar125WorkspaceCvRoute
  '/{-$locale}/workspace/finances': typeof Char123LocaleChar125WorkspaceFinancesRoute
  '/{-$locale}/workspace/fitness': typeof Char123LocaleChar125WorkspaceFitnessRoute
  '/{-$locale}/workspace/inventory': typeof Char123LocaleChar125WorkspaceInventoryRoute
  '/{-$locale}/workspace/logs': typeof Char123LocaleChar125WorkspaceLogsRoute
  '/{-$locale}/workspace/media': typeof Char123LocaleChar125WorkspaceMediaRoute
  '/{-$locale}/workspace/medical': typeof Char123LocaleChar125WorkspaceMedicalRoute
  '/{-$locale}/workspace/projects': typeof Char123LocaleChar125WorkspaceProjectsRoute
  '/{-$locale}/workspace/software': typeof Char123LocaleChar125WorkspaceSoftwareRoute
  '/{-$locale}/workspace/tax': typeof Char123LocaleChar125WorkspaceTaxRoute
  '/{-$locale}/workspace/todos': typeof Char123LocaleChar125WorkspaceTodosRoute
  '/{-$locale}/workspace/travel': typeof Char123LocaleChar125WorkspaceTravelRoute
  '/{-$locale}/workspace/visitor-chats': typeof Char123LocaleChar125WorkspaceVisitorChatsRoute
  '/{-$locale}/workspace/': typeof Char123LocaleChar125WorkspaceIndexRoute
  '/{-$locale}/workspace/assistant/$chatId': typeof Char123LocaleChar125WorkspaceAssistantChatIdRoute
  '/{-$locale}/workspace/inventory/$itemId': typeof Char123LocaleChar125WorkspaceInventoryItemIdRoute
  '/{-$locale}/workspace/projects/$projectId': typeof Char123LocaleChar125WorkspaceProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/file-uploads': typeof ApiFileUploadsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/tts': typeof ApiTtsRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/cv': typeof Char123LocaleChar125CvRoute
  '/{-$locale}/datenschutz': typeof Char123LocaleChar125DatenschutzRoute
  '/{-$locale}/impressum': typeof Char123LocaleChar125ImpressumRoute
  '/{-$locale}/projects': typeof Char123LocaleChar125ProjectsRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/api/file-uploads/$fileUploadId': typeof ApiFileUploadsFileUploadIdRoute
  '/{-$locale}/workspace/compass': typeof Char123LocaleChar125WorkspaceCompassRoute
  '/{-$locale}/workspace/cv': typeof Char123LocaleChar125WorkspaceCvRoute
  '/{-$locale}/workspace/finances': typeof Char123LocaleChar125WorkspaceFinancesRoute
  '/{-$locale}/workspace/fitness': typeof Char123LocaleChar125WorkspaceFitnessRoute
  '/{-$locale}/workspace/inventory': typeof Char123LocaleChar125WorkspaceInventoryRoute
  '/{-$locale}/workspace/logs': typeof Char123LocaleChar125WorkspaceLogsRoute
  '/{-$locale}/workspace/media': typeof Char123LocaleChar125WorkspaceMediaRoute
  '/{-$locale}/workspace/medical': typeof Char123LocaleChar125WorkspaceMedicalRoute
  '/{-$locale}/workspace/projects': typeof Char123LocaleChar125WorkspaceProjectsRoute
  '/{-$locale}/workspace/software': typeof Char123LocaleChar125WorkspaceSoftwareRoute
  '/{-$locale}/workspace/tax': typeof Char123LocaleChar125WorkspaceTaxRoute
  '/{-$locale}/workspace/todos': typeof Char123LocaleChar125WorkspaceTodosRoute
  '/{-$locale}/workspace/travel': typeof Char123LocaleChar125WorkspaceTravelRoute
  '/{-$locale}/workspace/visitor-chats': typeof Char123LocaleChar125WorkspaceVisitorChatsRoute
  '/{-$locale}/workspace': typeof Char123LocaleChar125WorkspaceIndexRoute
  '/{-$locale}/workspace/assistant/$chatId': typeof Char123LocaleChar125WorkspaceAssistantChatIdRoute
  '/{-$locale}/workspace/inventory/$itemId': typeof Char123LocaleChar125WorkspaceInventoryItemIdRoute
  '/{-$locale}/workspace/projects/$projectId': typeof Char123LocaleChar125WorkspaceProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/api/file-uploads': typeof ApiFileUploadsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/tts': typeof ApiTtsRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/cv': typeof Char123LocaleChar125CvRoute
  '/{-$locale}/datenschutz': typeof Char123LocaleChar125DatenschutzRoute
  '/{-$locale}/impressum': typeof Char123LocaleChar125ImpressumRoute
  '/{-$locale}/projects': typeof Char123LocaleChar125ProjectsRoute
  '/{-$locale}/workspace': typeof Char123LocaleChar125WorkspaceRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/file-uploads_/$fileUploadId': typeof ApiFileUploadsFileUploadIdRoute
  '/{-$locale}/workspace/compass': typeof Char123LocaleChar125WorkspaceCompassRoute
  '/{-$locale}/workspace/cv': typeof Char123LocaleChar125WorkspaceCvRoute
  '/{-$locale}/workspace/finances': typeof Char123LocaleChar125WorkspaceFinancesRoute
  '/{-$locale}/workspace/fitness': typeof Char123LocaleChar125WorkspaceFitnessRoute
  '/{-$locale}/workspace/inventory': typeof Char123LocaleChar125WorkspaceInventoryRoute
  '/{-$locale}/workspace/logs': typeof Char123LocaleChar125WorkspaceLogsRoute
  '/{-$locale}/workspace/media': typeof Char123LocaleChar125WorkspaceMediaRoute
  '/{-$locale}/workspace/medical': typeof Char123LocaleChar125WorkspaceMedicalRoute
  '/{-$locale}/workspace/projects': typeof Char123LocaleChar125WorkspaceProjectsRoute
  '/{-$locale}/workspace/software': typeof Char123LocaleChar125WorkspaceSoftwareRoute
  '/{-$locale}/workspace/tax': typeof Char123LocaleChar125WorkspaceTaxRoute
  '/{-$locale}/workspace/todos': typeof Char123LocaleChar125WorkspaceTodosRoute
  '/{-$locale}/workspace/travel': typeof Char123LocaleChar125WorkspaceTravelRoute
  '/{-$locale}/workspace/visitor-chats': typeof Char123LocaleChar125WorkspaceVisitorChatsRoute
  '/{-$locale}/workspace/': typeof Char123LocaleChar125WorkspaceIndexRoute
  '/{-$locale}/workspace/assistant/$chatId': typeof Char123LocaleChar125WorkspaceAssistantChatIdRoute
  '/{-$locale}/workspace/inventory_/$itemId': typeof Char123LocaleChar125WorkspaceInventoryItemIdRoute
  '/{-$locale}/workspace/projects_/$projectId': typeof Char123LocaleChar125WorkspaceProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}'
    | '/api/file-uploads'
    | '/api/graphql'
    | '/api/health'
    | '/api/stream'
    | '/api/tts'
    | '/{-$locale}/about'
    | '/{-$locale}/cv'
    | '/{-$locale}/datenschutz'
    | '/{-$locale}/impressum'
    | '/{-$locale}/projects'
    | '/{-$locale}/workspace'
    | '/{-$locale}/'
    | '/api/file-uploads/$fileUploadId'
    | '/{-$locale}/workspace/compass'
    | '/{-$locale}/workspace/cv'
    | '/{-$locale}/workspace/finances'
    | '/{-$locale}/workspace/fitness'
    | '/{-$locale}/workspace/inventory'
    | '/{-$locale}/workspace/logs'
    | '/{-$locale}/workspace/media'
    | '/{-$locale}/workspace/medical'
    | '/{-$locale}/workspace/projects'
    | '/{-$locale}/workspace/software'
    | '/{-$locale}/workspace/tax'
    | '/{-$locale}/workspace/todos'
    | '/{-$locale}/workspace/travel'
    | '/{-$locale}/workspace/visitor-chats'
    | '/{-$locale}/workspace/'
    | '/{-$locale}/workspace/assistant/$chatId'
    | '/{-$locale}/workspace/inventory/$itemId'
    | '/{-$locale}/workspace/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/file-uploads'
    | '/api/graphql'
    | '/api/health'
    | '/api/stream'
    | '/api/tts'
    | '/{-$locale}/about'
    | '/{-$locale}/cv'
    | '/{-$locale}/datenschutz'
    | '/{-$locale}/impressum'
    | '/{-$locale}/projects'
    | '/{-$locale}'
    | '/api/file-uploads/$fileUploadId'
    | '/{-$locale}/workspace/compass'
    | '/{-$locale}/workspace/cv'
    | '/{-$locale}/workspace/finances'
    | '/{-$locale}/workspace/fitness'
    | '/{-$locale}/workspace/inventory'
    | '/{-$locale}/workspace/logs'
    | '/{-$locale}/workspace/media'
    | '/{-$locale}/workspace/medical'
    | '/{-$locale}/workspace/projects'
    | '/{-$locale}/workspace/software'
    | '/{-$locale}/workspace/tax'
    | '/{-$locale}/workspace/todos'
    | '/{-$locale}/workspace/travel'
    | '/{-$locale}/workspace/visitor-chats'
    | '/{-$locale}/workspace'
    | '/{-$locale}/workspace/assistant/$chatId'
    | '/{-$locale}/workspace/inventory/$itemId'
    | '/{-$locale}/workspace/projects/$projectId'
  id:
    | '__root__'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}'
    | '/api/file-uploads'
    | '/api/graphql'
    | '/api/health'
    | '/api/stream'
    | '/api/tts'
    | '/{-$locale}/about'
    | '/{-$locale}/cv'
    | '/{-$locale}/datenschutz'
    | '/{-$locale}/impressum'
    | '/{-$locale}/projects'
    | '/{-$locale}/workspace'
    | '/{-$locale}/'
    | '/api/file-uploads_/$fileUploadId'
    | '/{-$locale}/workspace/compass'
    | '/{-$locale}/workspace/cv'
    | '/{-$locale}/workspace/finances'
    | '/{-$locale}/workspace/fitness'
    | '/{-$locale}/workspace/inventory'
    | '/{-$locale}/workspace/logs'
    | '/{-$locale}/workspace/media'
    | '/{-$locale}/workspace/medical'
    | '/{-$locale}/workspace/projects'
    | '/{-$locale}/workspace/software'
    | '/{-$locale}/workspace/tax'
    | '/{-$locale}/workspace/todos'
    | '/{-$locale}/workspace/travel'
    | '/{-$locale}/workspace/visitor-chats'
    | '/{-$locale}/workspace/'
    | '/{-$locale}/workspace/assistant/$chatId'
    | '/{-$locale}/workspace/inventory_/$itemId'
    | '/{-$locale}/workspace/projects_/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
  ApiFileUploadsRoute: typeof ApiFileUploadsRoute
  ApiGraphqlRoute: typeof ApiGraphqlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiFileUploadsFileUploadIdRoute: typeof ApiFileUploadsFileUploadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/workspace': {
      id: '/{-$locale}/workspace'
      path: '/workspace'
      fullPath: '/{-$locale}/workspace'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/projects': {
      id: '/{-$locale}/projects'
      path: '/projects'
      fullPath: '/{-$locale}/projects'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/impressum': {
      id: '/{-$locale}/impressum'
      path: '/impressum'
      fullPath: '/{-$locale}/impressum'
      preLoaderRoute: typeof Char123LocaleChar125ImpressumRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/datenschutz': {
      id: '/{-$locale}/datenschutz'
      path: '/datenschutz'
      fullPath: '/{-$locale}/datenschutz'
      preLoaderRoute: typeof Char123LocaleChar125DatenschutzRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/cv': {
      id: '/{-$locale}/cv'
      path: '/cv'
      fullPath: '/{-$locale}/cv'
      preLoaderRoute: typeof Char123LocaleChar125CvRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graphql': {
      id: '/api/graphql'
      path: '/api/graphql'
      fullPath: '/api/graphql'
      preLoaderRoute: typeof ApiGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file-uploads': {
      id: '/api/file-uploads'
      path: '/api/file-uploads'
      fullPath: '/api/file-uploads'
      preLoaderRoute: typeof ApiFileUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/workspace/': {
      id: '/{-$locale}/workspace/'
      path: '/'
      fullPath: '/{-$locale}/workspace/'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceIndexRouteImport
      parentRoute: typeof Char123LocaleChar125WorkspaceRoute
    }
    '/{-$locale}/workspace/visitor-chats': {
      id: '/{-$locale}/workspace/visitor-chats'
      path: '/visitor-chats'
      fullPath: '/{-$locale}/workspace/visitor-chats'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceVisitorChatsRouteImport
      parentRoute: typeof Char123LocaleChar125WorkspaceRoute
    }
    '/{-$locale}/workspace/travel': {
      id: '/{-$locale}/workspace/travel'
      path: '/travel'
      fullPath: '/{-$locale}/workspace/travel'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceTravelRouteImport
      parentRoute: typeof Char123LocaleChar125WorkspaceRoute
    }
    '/{-$locale}/workspace/todos': {
      id: '/{-$locale}/workspace/todos'
      path: '/todos'
      fullPath: '/{-$locale}/workspace/todos'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceTodosRouteImport
      parentRoute: typeof Char123LocaleChar125WorkspaceRoute
    }
    '/{-$locale}/workspace/tax': {
      id: '/{-$locale}/workspace/tax'
      path: '/tax'
      fullPath: '/{-$locale}/workspace/tax'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceTaxRouteImport
      parentRoute: typeof Char123LocaleChar125WorkspaceRoute
    }
    '/{-$locale}/workspace/software': {
      id: '/{-$locale}/workspace/software'
      path: '/software'
      fullPath: '/{-$locale}/workspace/software'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceSoftwareRouteImport
      parentRoute: typeof Char123LocaleChar125WorkspaceRoute
    }
    '/{-$locale}/workspace/projects': {
      id: '/{-$locale}/workspace/projects'
      path: '/projects'
      fullPath: '/{-$locale}/workspace/projects'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceProjectsRouteImport
      parentRoute: typeof Char123LocaleChar125WorkspaceRoute
    }
    '/{-$locale}/workspace/medical': {
      id: '/{-$locale}/workspace/medical'
      path: '/medical'
      fullPath: '/{-$locale}/workspace/medical'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceMedicalRouteImport
      parentRoute: typeof Char123LocaleChar125WorkspaceRoute
    }
    '/{-$locale}/workspace/media': {
      id: '/{-$locale}/workspace/media'
      path: '/media'
      fullPath: '/{-$locale}/workspace/media'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceMediaRouteImport
      parentRoute: typeof Char123LocaleChar125WorkspaceRoute
    }
    '/{-$locale}/workspace/logs': {
      id: '/{-$locale}/workspace/logs'
      path: '/logs'
      fullPath: '/{-$locale}/workspace/logs'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceLogsRouteImport
      parentRoute: typeof Char123LocaleChar125WorkspaceRoute
    }
    '/{-$locale}/workspace/inventory': {
      id: '/{-$locale}/workspace/inventory'
      path: '/inventory'
      fullPath: '/{-$locale}/workspace/inventory'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceInventoryRouteImport
      parentRoute: typeof Char123LocaleChar125WorkspaceRoute
    }
    '/{-$locale}/workspace/fitness': {
      id: '/{-$locale}/workspace/fitness'
      path: '/fitness'
      fullPath: '/{-$locale}/workspace/fitness'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceFitnessRouteImport
      parentRoute: typeof Char123LocaleChar125WorkspaceRoute
    }
    '/{-$locale}/workspace/finances': {
      id: '/{-$locale}/workspace/finances'
      path: '/finances'
      fullPath: '/{-$locale}/workspace/finances'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceFinancesRouteImport
      parentRoute: typeof Char123LocaleChar125WorkspaceRoute
    }
    '/{-$locale}/workspace/cv': {
      id: '/{-$locale}/workspace/cv'
      path: '/cv'
      fullPath: '/{-$locale}/workspace/cv'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceCvRouteImport
      parentRoute: typeof Char123LocaleChar125WorkspaceRoute
    }
    '/{-$locale}/workspace/compass': {
      id: '/{-$locale}/workspace/compass'
      path: '/compass'
      fullPath: '/{-$locale}/workspace/compass'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceCompassRouteImport
      parentRoute: typeof Char123LocaleChar125WorkspaceRoute
    }
    '/api/file-uploads_/$fileUploadId': {
      id: '/api/file-uploads_/$fileUploadId'
      path: '/api/file-uploads/$fileUploadId'
      fullPath: '/api/file-uploads/$fileUploadId'
      preLoaderRoute: typeof ApiFileUploadsFileUploadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/workspace/projects_/$projectId': {
      id: '/{-$locale}/workspace/projects_/$projectId'
      path: '/projects/$projectId'
      fullPath: '/{-$locale}/workspace/projects/$projectId'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceProjectsProjectIdRouteImport
      parentRoute: typeof Char123LocaleChar125WorkspaceRoute
    }
    '/{-$locale}/workspace/inventory_/$itemId': {
      id: '/{-$locale}/workspace/inventory_/$itemId'
      path: '/inventory/$itemId'
      fullPath: '/{-$locale}/workspace/inventory/$itemId'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceInventoryItemIdRouteImport
      parentRoute: typeof Char123LocaleChar125WorkspaceRoute
    }
    '/{-$locale}/workspace/assistant/$chatId': {
      id: '/{-$locale}/workspace/assistant/$chatId'
      path: '/assistant/$chatId'
      fullPath: '/{-$locale}/workspace/assistant/$chatId'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceAssistantChatIdRouteImport
      parentRoute: typeof Char123LocaleChar125WorkspaceRoute
    }
  }
}

interface Char123LocaleChar125WorkspaceRouteChildren {
  Char123LocaleChar125WorkspaceCompassRoute: typeof Char123LocaleChar125WorkspaceCompassRoute
  Char123LocaleChar125WorkspaceCvRoute: typeof Char123LocaleChar125WorkspaceCvRoute
  Char123LocaleChar125WorkspaceFinancesRoute: typeof Char123LocaleChar125WorkspaceFinancesRoute
  Char123LocaleChar125WorkspaceFitnessRoute: typeof Char123LocaleChar125WorkspaceFitnessRoute
  Char123LocaleChar125WorkspaceInventoryRoute: typeof Char123LocaleChar125WorkspaceInventoryRoute
  Char123LocaleChar125WorkspaceLogsRoute: typeof Char123LocaleChar125WorkspaceLogsRoute
  Char123LocaleChar125WorkspaceMediaRoute: typeof Char123LocaleChar125WorkspaceMediaRoute
  Char123LocaleChar125WorkspaceMedicalRoute: typeof Char123LocaleChar125WorkspaceMedicalRoute
  Char123LocaleChar125WorkspaceProjectsRoute: typeof Char123LocaleChar125WorkspaceProjectsRoute
  Char123LocaleChar125WorkspaceSoftwareRoute: typeof Char123LocaleChar125WorkspaceSoftwareRoute
  Char123LocaleChar125WorkspaceTaxRoute: typeof Char123LocaleChar125WorkspaceTaxRoute
  Char123LocaleChar125WorkspaceTodosRoute: typeof Char123LocaleChar125WorkspaceTodosRoute
  Char123LocaleChar125WorkspaceTravelRoute: typeof Char123LocaleChar125WorkspaceTravelRoute
  Char123LocaleChar125WorkspaceVisitorChatsRoute: typeof Char123LocaleChar125WorkspaceVisitorChatsRoute
  Char123LocaleChar125WorkspaceIndexRoute: typeof Char123LocaleChar125WorkspaceIndexRoute
  Char123LocaleChar125WorkspaceAssistantChatIdRoute: typeof Char123LocaleChar125WorkspaceAssistantChatIdRoute
  Char123LocaleChar125WorkspaceInventoryItemIdRoute: typeof Char123LocaleChar125WorkspaceInventoryItemIdRoute
  Char123LocaleChar125WorkspaceProjectsProjectIdRoute: typeof Char123LocaleChar125WorkspaceProjectsProjectIdRoute
}

const Char123LocaleChar125WorkspaceRouteChildren: Char123LocaleChar125WorkspaceRouteChildren =
  {
    Char123LocaleChar125WorkspaceCompassRoute:
      Char123LocaleChar125WorkspaceCompassRoute,
    Char123LocaleChar125WorkspaceCvRoute: Char123LocaleChar125WorkspaceCvRoute,
    Char123LocaleChar125WorkspaceFinancesRoute:
      Char123LocaleChar125WorkspaceFinancesRoute,
    Char123LocaleChar125WorkspaceFitnessRoute:
      Char123LocaleChar125WorkspaceFitnessRoute,
    Char123LocaleChar125WorkspaceInventoryRoute:
      Char123LocaleChar125WorkspaceInventoryRoute,
    Char123LocaleChar125WorkspaceLogsRoute:
      Char123LocaleChar125WorkspaceLogsRoute,
    Char123LocaleChar125WorkspaceMediaRoute:
      Char123LocaleChar125WorkspaceMediaRoute,
    Char123LocaleChar125WorkspaceMedicalRoute:
      Char123LocaleChar125WorkspaceMedicalRoute,
    Char123LocaleChar125WorkspaceProjectsRoute:
      Char123LocaleChar125WorkspaceProjectsRoute,
    Char123LocaleChar125WorkspaceSoftwareRoute:
      Char123LocaleChar125WorkspaceSoftwareRoute,
    Char123LocaleChar125WorkspaceTaxRoute:
      Char123LocaleChar125WorkspaceTaxRoute,
    Char123LocaleChar125WorkspaceTodosRoute:
      Char123LocaleChar125WorkspaceTodosRoute,
    Char123LocaleChar125WorkspaceTravelRoute:
      Char123LocaleChar125WorkspaceTravelRoute,
    Char123LocaleChar125WorkspaceVisitorChatsRoute:
      Char123LocaleChar125WorkspaceVisitorChatsRoute,
    Char123LocaleChar125WorkspaceIndexRoute:
      Char123LocaleChar125WorkspaceIndexRoute,
    Char123LocaleChar125WorkspaceAssistantChatIdRoute:
      Char123LocaleChar125WorkspaceAssistantChatIdRoute,
    Char123LocaleChar125WorkspaceInventoryItemIdRoute:
      Char123LocaleChar125WorkspaceInventoryItemIdRoute,
    Char123LocaleChar125WorkspaceProjectsProjectIdRoute:
      Char123LocaleChar125WorkspaceProjectsProjectIdRoute,
  }

const Char123LocaleChar125WorkspaceRouteWithChildren =
  Char123LocaleChar125WorkspaceRoute._addFileChildren(
    Char123LocaleChar125WorkspaceRouteChildren,
  )

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125CvRoute: typeof Char123LocaleChar125CvRoute
  Char123LocaleChar125DatenschutzRoute: typeof Char123LocaleChar125DatenschutzRoute
  Char123LocaleChar125ImpressumRoute: typeof Char123LocaleChar125ImpressumRoute
  Char123LocaleChar125ProjectsRoute: typeof Char123LocaleChar125ProjectsRoute
  Char123LocaleChar125WorkspaceRoute: typeof Char123LocaleChar125WorkspaceRouteWithChildren
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
  Char123LocaleChar125CvRoute: Char123LocaleChar125CvRoute,
  Char123LocaleChar125DatenschutzRoute: Char123LocaleChar125DatenschutzRoute,
  Char123LocaleChar125ImpressumRoute: Char123LocaleChar125ImpressumRoute,
  Char123LocaleChar125ProjectsRoute: Char123LocaleChar125ProjectsRoute,
  Char123LocaleChar125WorkspaceRoute:
    Char123LocaleChar125WorkspaceRouteWithChildren,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
  ApiFileUploadsRoute: ApiFileUploadsRoute,
  ApiGraphqlRoute: ApiGraphqlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiFileUploadsFileUploadIdRoute: ApiFileUploadsFileUploadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
