/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125ProjectsRouteImport } from './routes/{-$locale}/projects'
import { Route as Char123LocaleChar125ImpressumRouteImport } from './routes/{-$locale}/impressum'
import { Route as Char123LocaleChar125DatenschutzRouteImport } from './routes/{-$locale}/datenschutz'
import { Route as Char123LocaleChar125CvRouteImport } from './routes/{-$locale}/cv'
import { Route as Char123LocaleChar125ChatRouteImport } from './routes/{-$locale}/chat'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGraphqlRouteImport } from './routes/api/graphql'
import { Route as ApiFileUploadsRouteImport } from './routes/api/file-uploads'
import { Route as Char123LocaleChar125WorkspaceIndexRouteImport } from './routes/{-$locale}/workspace/index'
import { Route as Char123LocaleChar125WorkspaceTaxRouteImport } from './routes/{-$locale}/workspace/tax'
import { Route as Char123LocaleChar125WorkspaceSoftwareRouteImport } from './routes/{-$locale}/workspace/software'
import { Route as Char123LocaleChar125WorkspaceProjectsRouteImport } from './routes/{-$locale}/workspace/projects'
import { Route as Char123LocaleChar125WorkspaceMedicalRouteImport } from './routes/{-$locale}/workspace/medical'
import { Route as Char123LocaleChar125WorkspaceMediaRouteImport } from './routes/{-$locale}/workspace/media'
import { Route as Char123LocaleChar125WorkspaceFitnessRouteImport } from './routes/{-$locale}/workspace/fitness'
import { Route as Char123LocaleChar125WorkspaceFinancesRouteImport } from './routes/{-$locale}/workspace/finances'
import { Route as Char123LocaleChar125WorkspaceCvRouteImport } from './routes/{-$locale}/workspace/cv'
import { Route as Char123LocaleChar125WorkspaceAssistantRouteImport } from './routes/{-$locale}/workspace/assistant'
import { Route as ApiFileUploadsFileUploadIdRouteImport } from './routes/api/file-uploads_.$fileUploadId'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ProjectsRoute =
  Char123LocaleChar125ProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ImpressumRoute =
  Char123LocaleChar125ImpressumRouteImport.update({
    id: '/impressum',
    path: '/impressum',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125DatenschutzRoute =
  Char123LocaleChar125DatenschutzRouteImport.update({
    id: '/datenschutz',
    path: '/datenschutz',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125CvRoute = Char123LocaleChar125CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => Char123LocaleChar125Route,
} as any)
const Char123LocaleChar125ChatRoute =
  Char123LocaleChar125ChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphqlRoute = ApiGraphqlRouteImport.update({
  id: '/api/graphql',
  path: '/api/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileUploadsRoute = ApiFileUploadsRouteImport.update({
  id: '/api/file-uploads',
  path: '/api/file-uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125WorkspaceIndexRoute =
  Char123LocaleChar125WorkspaceIndexRouteImport.update({
    id: '/workspace/',
    path: '/workspace/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125WorkspaceTaxRoute =
  Char123LocaleChar125WorkspaceTaxRouteImport.update({
    id: '/workspace/tax',
    path: '/workspace/tax',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125WorkspaceSoftwareRoute =
  Char123LocaleChar125WorkspaceSoftwareRouteImport.update({
    id: '/workspace/software',
    path: '/workspace/software',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125WorkspaceProjectsRoute =
  Char123LocaleChar125WorkspaceProjectsRouteImport.update({
    id: '/workspace/projects',
    path: '/workspace/projects',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125WorkspaceMedicalRoute =
  Char123LocaleChar125WorkspaceMedicalRouteImport.update({
    id: '/workspace/medical',
    path: '/workspace/medical',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125WorkspaceMediaRoute =
  Char123LocaleChar125WorkspaceMediaRouteImport.update({
    id: '/workspace/media',
    path: '/workspace/media',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125WorkspaceFitnessRoute =
  Char123LocaleChar125WorkspaceFitnessRouteImport.update({
    id: '/workspace/fitness',
    path: '/workspace/fitness',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125WorkspaceFinancesRoute =
  Char123LocaleChar125WorkspaceFinancesRouteImport.update({
    id: '/workspace/finances',
    path: '/workspace/finances',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125WorkspaceCvRoute =
  Char123LocaleChar125WorkspaceCvRouteImport.update({
    id: '/workspace/cv',
    path: '/workspace/cv',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125WorkspaceAssistantRoute =
  Char123LocaleChar125WorkspaceAssistantRouteImport.update({
    id: '/workspace/assistant',
    path: '/workspace/assistant',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const ApiFileUploadsFileUploadIdRoute =
  ApiFileUploadsFileUploadIdRouteImport.update({
    id: '/api/file-uploads_/$fileUploadId',
    path: '/api/file-uploads/$fileUploadId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/api/file-uploads': typeof ApiFileUploadsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/chat': typeof Char123LocaleChar125ChatRoute
  '/{-$locale}/cv': typeof Char123LocaleChar125CvRoute
  '/{-$locale}/datenschutz': typeof Char123LocaleChar125DatenschutzRoute
  '/{-$locale}/impressum': typeof Char123LocaleChar125ImpressumRoute
  '/{-$locale}/projects': typeof Char123LocaleChar125ProjectsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/file-uploads/$fileUploadId': typeof ApiFileUploadsFileUploadIdRoute
  '/{-$locale}/workspace/assistant': typeof Char123LocaleChar125WorkspaceAssistantRoute
  '/{-$locale}/workspace/cv': typeof Char123LocaleChar125WorkspaceCvRoute
  '/{-$locale}/workspace/finances': typeof Char123LocaleChar125WorkspaceFinancesRoute
  '/{-$locale}/workspace/fitness': typeof Char123LocaleChar125WorkspaceFitnessRoute
  '/{-$locale}/workspace/media': typeof Char123LocaleChar125WorkspaceMediaRoute
  '/{-$locale}/workspace/medical': typeof Char123LocaleChar125WorkspaceMedicalRoute
  '/{-$locale}/workspace/projects': typeof Char123LocaleChar125WorkspaceProjectsRoute
  '/{-$locale}/workspace/software': typeof Char123LocaleChar125WorkspaceSoftwareRoute
  '/{-$locale}/workspace/tax': typeof Char123LocaleChar125WorkspaceTaxRoute
  '/{-$locale}/workspace/': typeof Char123LocaleChar125WorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/file-uploads': typeof ApiFileUploadsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/chat': typeof Char123LocaleChar125ChatRoute
  '/{-$locale}/cv': typeof Char123LocaleChar125CvRoute
  '/{-$locale}/datenschutz': typeof Char123LocaleChar125DatenschutzRoute
  '/{-$locale}/impressum': typeof Char123LocaleChar125ImpressumRoute
  '/{-$locale}/projects': typeof Char123LocaleChar125ProjectsRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/api/file-uploads/$fileUploadId': typeof ApiFileUploadsFileUploadIdRoute
  '/{-$locale}/workspace/assistant': typeof Char123LocaleChar125WorkspaceAssistantRoute
  '/{-$locale}/workspace/cv': typeof Char123LocaleChar125WorkspaceCvRoute
  '/{-$locale}/workspace/finances': typeof Char123LocaleChar125WorkspaceFinancesRoute
  '/{-$locale}/workspace/fitness': typeof Char123LocaleChar125WorkspaceFitnessRoute
  '/{-$locale}/workspace/media': typeof Char123LocaleChar125WorkspaceMediaRoute
  '/{-$locale}/workspace/medical': typeof Char123LocaleChar125WorkspaceMedicalRoute
  '/{-$locale}/workspace/projects': typeof Char123LocaleChar125WorkspaceProjectsRoute
  '/{-$locale}/workspace/software': typeof Char123LocaleChar125WorkspaceSoftwareRoute
  '/{-$locale}/workspace/tax': typeof Char123LocaleChar125WorkspaceTaxRoute
  '/{-$locale}/workspace': typeof Char123LocaleChar125WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/api/file-uploads': typeof ApiFileUploadsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/chat': typeof Char123LocaleChar125ChatRoute
  '/{-$locale}/cv': typeof Char123LocaleChar125CvRoute
  '/{-$locale}/datenschutz': typeof Char123LocaleChar125DatenschutzRoute
  '/{-$locale}/impressum': typeof Char123LocaleChar125ImpressumRoute
  '/{-$locale}/projects': typeof Char123LocaleChar125ProjectsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/file-uploads_/$fileUploadId': typeof ApiFileUploadsFileUploadIdRoute
  '/{-$locale}/workspace/assistant': typeof Char123LocaleChar125WorkspaceAssistantRoute
  '/{-$locale}/workspace/cv': typeof Char123LocaleChar125WorkspaceCvRoute
  '/{-$locale}/workspace/finances': typeof Char123LocaleChar125WorkspaceFinancesRoute
  '/{-$locale}/workspace/fitness': typeof Char123LocaleChar125WorkspaceFitnessRoute
  '/{-$locale}/workspace/media': typeof Char123LocaleChar125WorkspaceMediaRoute
  '/{-$locale}/workspace/medical': typeof Char123LocaleChar125WorkspaceMedicalRoute
  '/{-$locale}/workspace/projects': typeof Char123LocaleChar125WorkspaceProjectsRoute
  '/{-$locale}/workspace/software': typeof Char123LocaleChar125WorkspaceSoftwareRoute
  '/{-$locale}/workspace/tax': typeof Char123LocaleChar125WorkspaceTaxRoute
  '/{-$locale}/workspace/': typeof Char123LocaleChar125WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}'
    | '/api/file-uploads'
    | '/api/graphql'
    | '/api/health'
    | '/api/stream'
    | '/{-$locale}/about'
    | '/{-$locale}/chat'
    | '/{-$locale}/cv'
    | '/{-$locale}/datenschutz'
    | '/{-$locale}/impressum'
    | '/{-$locale}/projects'
    | '/{-$locale}/'
    | '/api/file-uploads/$fileUploadId'
    | '/{-$locale}/workspace/assistant'
    | '/{-$locale}/workspace/cv'
    | '/{-$locale}/workspace/finances'
    | '/{-$locale}/workspace/fitness'
    | '/{-$locale}/workspace/media'
    | '/{-$locale}/workspace/medical'
    | '/{-$locale}/workspace/projects'
    | '/{-$locale}/workspace/software'
    | '/{-$locale}/workspace/tax'
    | '/{-$locale}/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/file-uploads'
    | '/api/graphql'
    | '/api/health'
    | '/api/stream'
    | '/{-$locale}/about'
    | '/{-$locale}/chat'
    | '/{-$locale}/cv'
    | '/{-$locale}/datenschutz'
    | '/{-$locale}/impressum'
    | '/{-$locale}/projects'
    | '/{-$locale}'
    | '/api/file-uploads/$fileUploadId'
    | '/{-$locale}/workspace/assistant'
    | '/{-$locale}/workspace/cv'
    | '/{-$locale}/workspace/finances'
    | '/{-$locale}/workspace/fitness'
    | '/{-$locale}/workspace/media'
    | '/{-$locale}/workspace/medical'
    | '/{-$locale}/workspace/projects'
    | '/{-$locale}/workspace/software'
    | '/{-$locale}/workspace/tax'
    | '/{-$locale}/workspace'
  id:
    | '__root__'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}'
    | '/api/file-uploads'
    | '/api/graphql'
    | '/api/health'
    | '/api/stream'
    | '/{-$locale}/about'
    | '/{-$locale}/chat'
    | '/{-$locale}/cv'
    | '/{-$locale}/datenschutz'
    | '/{-$locale}/impressum'
    | '/{-$locale}/projects'
    | '/{-$locale}/'
    | '/api/file-uploads_/$fileUploadId'
    | '/{-$locale}/workspace/assistant'
    | '/{-$locale}/workspace/cv'
    | '/{-$locale}/workspace/finances'
    | '/{-$locale}/workspace/fitness'
    | '/{-$locale}/workspace/media'
    | '/{-$locale}/workspace/medical'
    | '/{-$locale}/workspace/projects'
    | '/{-$locale}/workspace/software'
    | '/{-$locale}/workspace/tax'
    | '/{-$locale}/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
  ApiFileUploadsRoute: typeof ApiFileUploadsRoute
  ApiGraphqlRoute: typeof ApiGraphqlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiFileUploadsFileUploadIdRoute: typeof ApiFileUploadsFileUploadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/projects': {
      id: '/{-$locale}/projects'
      path: '/projects'
      fullPath: '/{-$locale}/projects'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/impressum': {
      id: '/{-$locale}/impressum'
      path: '/impressum'
      fullPath: '/{-$locale}/impressum'
      preLoaderRoute: typeof Char123LocaleChar125ImpressumRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/datenschutz': {
      id: '/{-$locale}/datenschutz'
      path: '/datenschutz'
      fullPath: '/{-$locale}/datenschutz'
      preLoaderRoute: typeof Char123LocaleChar125DatenschutzRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/cv': {
      id: '/{-$locale}/cv'
      path: '/cv'
      fullPath: '/{-$locale}/cv'
      preLoaderRoute: typeof Char123LocaleChar125CvRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/chat': {
      id: '/{-$locale}/chat'
      path: '/chat'
      fullPath: '/{-$locale}/chat'
      preLoaderRoute: typeof Char123LocaleChar125ChatRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graphql': {
      id: '/api/graphql'
      path: '/api/graphql'
      fullPath: '/api/graphql'
      preLoaderRoute: typeof ApiGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file-uploads': {
      id: '/api/file-uploads'
      path: '/api/file-uploads'
      fullPath: '/api/file-uploads'
      preLoaderRoute: typeof ApiFileUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/workspace/': {
      id: '/{-$locale}/workspace/'
      path: '/workspace'
      fullPath: '/{-$locale}/workspace/'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/workspace/tax': {
      id: '/{-$locale}/workspace/tax'
      path: '/workspace/tax'
      fullPath: '/{-$locale}/workspace/tax'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceTaxRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/workspace/software': {
      id: '/{-$locale}/workspace/software'
      path: '/workspace/software'
      fullPath: '/{-$locale}/workspace/software'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceSoftwareRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/workspace/projects': {
      id: '/{-$locale}/workspace/projects'
      path: '/workspace/projects'
      fullPath: '/{-$locale}/workspace/projects'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceProjectsRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/workspace/medical': {
      id: '/{-$locale}/workspace/medical'
      path: '/workspace/medical'
      fullPath: '/{-$locale}/workspace/medical'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceMedicalRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/workspace/media': {
      id: '/{-$locale}/workspace/media'
      path: '/workspace/media'
      fullPath: '/{-$locale}/workspace/media'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceMediaRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/workspace/fitness': {
      id: '/{-$locale}/workspace/fitness'
      path: '/workspace/fitness'
      fullPath: '/{-$locale}/workspace/fitness'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceFitnessRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/workspace/finances': {
      id: '/{-$locale}/workspace/finances'
      path: '/workspace/finances'
      fullPath: '/{-$locale}/workspace/finances'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceFinancesRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/workspace/cv': {
      id: '/{-$locale}/workspace/cv'
      path: '/workspace/cv'
      fullPath: '/{-$locale}/workspace/cv'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceCvRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/workspace/assistant': {
      id: '/{-$locale}/workspace/assistant'
      path: '/workspace/assistant'
      fullPath: '/{-$locale}/workspace/assistant'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceAssistantRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/api/file-uploads_/$fileUploadId': {
      id: '/api/file-uploads_/$fileUploadId'
      path: '/api/file-uploads/$fileUploadId'
      fullPath: '/api/file-uploads/$fileUploadId'
      preLoaderRoute: typeof ApiFileUploadsFileUploadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125ChatRoute: typeof Char123LocaleChar125ChatRoute
  Char123LocaleChar125CvRoute: typeof Char123LocaleChar125CvRoute
  Char123LocaleChar125DatenschutzRoute: typeof Char123LocaleChar125DatenschutzRoute
  Char123LocaleChar125ImpressumRoute: typeof Char123LocaleChar125ImpressumRoute
  Char123LocaleChar125ProjectsRoute: typeof Char123LocaleChar125ProjectsRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125WorkspaceAssistantRoute: typeof Char123LocaleChar125WorkspaceAssistantRoute
  Char123LocaleChar125WorkspaceCvRoute: typeof Char123LocaleChar125WorkspaceCvRoute
  Char123LocaleChar125WorkspaceFinancesRoute: typeof Char123LocaleChar125WorkspaceFinancesRoute
  Char123LocaleChar125WorkspaceFitnessRoute: typeof Char123LocaleChar125WorkspaceFitnessRoute
  Char123LocaleChar125WorkspaceMediaRoute: typeof Char123LocaleChar125WorkspaceMediaRoute
  Char123LocaleChar125WorkspaceMedicalRoute: typeof Char123LocaleChar125WorkspaceMedicalRoute
  Char123LocaleChar125WorkspaceProjectsRoute: typeof Char123LocaleChar125WorkspaceProjectsRoute
  Char123LocaleChar125WorkspaceSoftwareRoute: typeof Char123LocaleChar125WorkspaceSoftwareRoute
  Char123LocaleChar125WorkspaceTaxRoute: typeof Char123LocaleChar125WorkspaceTaxRoute
  Char123LocaleChar125WorkspaceIndexRoute: typeof Char123LocaleChar125WorkspaceIndexRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
  Char123LocaleChar125ChatRoute: Char123LocaleChar125ChatRoute,
  Char123LocaleChar125CvRoute: Char123LocaleChar125CvRoute,
  Char123LocaleChar125DatenschutzRoute: Char123LocaleChar125DatenschutzRoute,
  Char123LocaleChar125ImpressumRoute: Char123LocaleChar125ImpressumRoute,
  Char123LocaleChar125ProjectsRoute: Char123LocaleChar125ProjectsRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  Char123LocaleChar125WorkspaceAssistantRoute:
    Char123LocaleChar125WorkspaceAssistantRoute,
  Char123LocaleChar125WorkspaceCvRoute: Char123LocaleChar125WorkspaceCvRoute,
  Char123LocaleChar125WorkspaceFinancesRoute:
    Char123LocaleChar125WorkspaceFinancesRoute,
  Char123LocaleChar125WorkspaceFitnessRoute:
    Char123LocaleChar125WorkspaceFitnessRoute,
  Char123LocaleChar125WorkspaceMediaRoute:
    Char123LocaleChar125WorkspaceMediaRoute,
  Char123LocaleChar125WorkspaceMedicalRoute:
    Char123LocaleChar125WorkspaceMedicalRoute,
  Char123LocaleChar125WorkspaceProjectsRoute:
    Char123LocaleChar125WorkspaceProjectsRoute,
  Char123LocaleChar125WorkspaceSoftwareRoute:
    Char123LocaleChar125WorkspaceSoftwareRoute,
  Char123LocaleChar125WorkspaceTaxRoute: Char123LocaleChar125WorkspaceTaxRoute,
  Char123LocaleChar125WorkspaceIndexRoute:
    Char123LocaleChar125WorkspaceIndexRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
  ApiFileUploadsRoute: ApiFileUploadsRoute,
  ApiGraphqlRoute: ApiGraphqlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiFileUploadsFileUploadIdRoute: ApiFileUploadsFileUploadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
